# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('user_id', models.CharField(max_length=20, verbose_name='用户id')),
                ('role', models.CharField(default='1', max_length=3, verbose_name='管理员')),
            ],
            options={
                'db_table': 'ruler',
            },
        ),
    ]
