# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-23 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='用户id')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('tel', models.CharField(max_length=11, null=True, verbose_name='电话号码')),
                ('mail', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('role', models.CharField(default='2', max_length=3, verbose_name='快递员')),
            ],
            options={
                'db_table': 'courier',
            },
        ),
        migrations.CreateModel(
            name='CourierReality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('gender', models.CharField(max_length=6, verbose_name='性别')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号码')),
                ('nationality', models.CharField(max_length=255, verbose_name='民族')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courier.Courier', verbose_name='快递员')),
            ],
            options={
                'db_table': 'courier_reality',
            },
        ),
    ]
